[package]
name = "game-the-curse-of-the-headless-goose"
version = "0.1.0"
edition = "2024"
publish = false

# Profiles taken from https://github.com/rp-rs/rp2040-project-template

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
ascon = "0.4.0"
cortex-m-rt = "0.7.3"
defmt-rtt = "1"
eeprom24x = "0.7.2"
eh0 = { package = "embedded-hal", version = "0.2" }
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
itoa = "1.0.15"
log = "0.4.29"
mipidsi = "0.9.0"
nb = "1.1.0"
panic-halt = "1"
rand_core = "0.6"

[target.'cfg(target_os="none")'.dependencies]
waveshare-rp2040-zero = "0.8"

[target.'cfg(not(target_os="none"))'.dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
fastrand = "2.3.0"
